/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    CHANGES: typeof import('./node_modules/highlight.js/CHANGES.md')['default']
    ColourfulText: typeof import('./colourful-text/ColourfulText.vue')['default']
    copy: typeof import('./Demo copy.vue')['default']
    Counter: typeof import('./node_modules/unplugin-vue-markdown/examples/vite/Counter.vue')['default']
    Counter2: typeof import('./node_modules/unplugin-vue-markdown/examples/vite/Counter2.vue')['default']
    Demo: typeof import('./Demo.vue')['default']
    DemoTest: typeof import('./demo-test.vue')['default']
    Hi: typeof import('./node_modules/unplugin-vue-markdown/examples/vue-cli/src/Hi.md')['default']
    LICENSE: typeof import('./node_modules/vite/LICENSE.md')['default']
    NCard: typeof import('naive-ui')['NCard']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Pages: typeof import('./node_modules/unplugin-vue-markdown/examples/vite/pages/index.md')['default']
    README: typeof import('./node_modules/@vitejs/plugin-vue/README.md')['default']
    'README.zhCN': typeof import('./node_modules/naive-ui/README.zh-CN.md')['default']
    Route: typeof import('./node_modules/unplugin-vue-markdown/examples/vite/pages/route.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SECURITY: typeof import('./node_modules/highlight.js/SECURITY.md')['default']
    Simple: typeof import('./node_modules/unplugin-vue-markdown/test/fixtures/simple.md')['default']
    SUPPORTED_LANGUAGES: typeof import('./node_modules/highlight.js/SUPPORTED_LANGUAGES.md')['default']
    SvgIcon: typeof import('./svg-icon.tsx')['default']
    Test: typeof import('./test.md')['default']
    VERSION_10_UPGRADE: typeof import('./node_modules/highlight.js/VERSION_10_UPGRADE.md')['default']
    VERSION_11_UPGRADE: typeof import('./node_modules/highlight.js/VERSION_11_UPGRADE.md')['default']
  }
}
